[build]
  publish = "website"
  functions = "netlify/functions"

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/api/stripe/webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
